spring:
  application:
    name: student-mapping
  datasource:
    url: jdbc:mysql://localhost:3306/mapping?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082